### ISSUE TITLE
The path to 1.0

### ISSUE THREAD

**Issue by razziel89** [razziel89/mdslw#18]
Before a 1.0 release that comes with some stability guarantees, some things should be taken care of. This is issue collects all such tasks.

- [x] #16: handle features in a more sustainable way
- [x] #15: support hierarchical configuration files
- [x] #17: simplify supporting new extensions
- [x] #19: provide details about deviations from desired state

**Comment by razziel89** [comment]
Everything has been implemented. Release 0.11.0 will follow soon. It will be left as is for a while and potentially turned into the 1.0.0 release later on. Some more changes might be incoming, but I do not expect many.

**Comment by razziel89** [comment]
Two more changes are still planned before version 1.0:

1. The `--features` need to be recast as different flags. The link-related ones should become arguments to `--link-actions`. The whitespace-related ones should become arguments to the `--whitespace` flag.
2. A simple way to define per-file configurations would be nice. The frontmatter can contain a key `mdslw-toml` followed by `|` or `|-`. Everything at the same indentation level as the next non-empty line will be extracted as a toml config file content valid only for this file.

**Comment by razziel89** [comment]
Per-file configurations have been added in `0.16.0`.
